### ISSUE TITLE
How to Reduce Latency for First Frame Capture with UVC Camera?

### ISSUE THREAD

**Issue by kboseong** [tiagocoutinho/linuxpy#13]
First of all, thank you for the excellent work you are doing with this project.

I am currently working on a project where I need to capture a photo as soon as an object is detected by a specific sensor. 
After capturing the photo, the system should wait for the next trigger. 
I am using a regular UVC camera instead of a machine vision camera and need the fastest possible frame acquisition method in Python.

With the code below, it takes about 1 second to obtain the first frame from the device. 
While the time to acquire subsequent frames is significantly reduced, I need to speed up the acquisition of the first frame.

cam = Device.from_id(0)
cam.open()
source = VideoCapture(cam)

with source:
    for frame in source:
        data = frame.data
        break

**Comment by tiagocoutinho** [comment]
That's a very good question.
IMHO, there are 2 things that take time:
1. opening the device object
2. initialize a capture stream

The first you already solved by preemptively opening the device.

The second can be solved by acquiring a dumb image at the start:

```python
cam = Device.from_id(0)
cam.open()  # takes ~0.12s on my laptop uvc cam
stream = iter(cam)
next(stream) # take a dumb frame just to arm de camera (takes ~0.3s for me)

# now, each time you receive a trigger you can take the image with:
def on_trigger():
    frame = next(stream)
```

**Comment by kboseong** [comment]
Great! Your explanation and code suggestions are incredibly helpful.

Thanks again for your assistance and for the great work on this project.

**Comment by kboseong** [comment]
Hi, how can I free camera buffer memory before I call next(stream)? 
Thanks
