### ISSUE TITLE
Pypi version for release 0.1.0 faulty

### ISSUE THREAD

**Issue by preste-thsou** [tiagocoutinho/linuxpy#14]
Hello,

I just would like to point out that the pypi version published for release 0.1.0 (compatible with python 3.8) is incomplete, missing 4 folders (video, usb, codegen and input) compared to the source code. It makes the package installed with pip for python 3.8 not usable.

**Comment by StefanBruens** [comment]
This can be trivially fixed by changing the include in pyproject.toml to "linuxpy*".

**Comment by tiagocoutinho** [comment]
Indeed. Thanks for pointing it out.
It looks like I fixed in for 0.4.0.

I should probably remove unusable versions from pypi.

Do you need a version compatible with 3.8? Otherwise could we close this issue?

**Comment by preste-thsou** [comment]
Hello,

Many thanks for the replies. I reverted back to v4l2py, it covers the function I needed with python 3.8, so I have no particular need here, I was just pointing it out for future users stuck with python 3.8 for one reason or another, and I suggest indeed, either to remove this version if it's not functional, or to correct the 0.1.0 release in Pypi, but it's obviously up to you !

Regards,

Thibaut

**Comment by tiagocoutinho** [comment]
Ok, I deleted those versions from pypi.

**Comment by StefanBruens** [comment]
Have you tried building 0.10.0 from a clean git checkout? Most importantly, with an empty build directory?

When I  use the following command, only the linuxpy directory will be included in the wheel, but none of its subdirectories:

`/usr/bin/python3.10 -mpip wheel --verbose --progress-bar off --disable-pip-version-check --use-pep517 --no-build-isolation --no-deps --wheel-dir ./build .`

**Comment by tiagocoutinho** [comment]
Good point @StefanBruens 
Sorry for the late reply. I missed your comment cause I closed the issue
It should be fixed now in master and version 0.15.0
