### ISSUE TITLE
v4l2py-ctl example references LegacyControl

### ISSUE THREAD

**Issue by StefanBruens** [tiagocoutinho/linuxpy#15]
The LegacyControl was removed from video.device:

https://github.com/tiagocoutinho/linuxpy/commit/641e07da1ce444fae7391f168c0b0a61221c0171#diff-79d8ee3fcd63f8ac015721cbd6ba05fa6b0023a32f0f462a7503c2cce4b6e75aL1248

Probably, all instances of LegacyControl and the `--legacy` option should be removed.

**Comment by brainey** [comment]
Removing LegacyControl break the v4l2py-ctl.py example.
