### ISSUE TITLE
iter_video_capture_devices not finding devices on Ubuntu 24 (Python 3.12)

### ISSUE THREAD

**Issue by Robolightning** [tiagocoutinho/linuxpy#46]
iter_video_capture_devices from linuxpy.video.device do not finding any devices on Ubuntu 24 (Python 3.12)

**Comment by Robolightning** [comment]
![image](https://github.com/user-attachments/assets/ef73651e-f6f1-4876-a7dd-84cbd0f0e5a2)
My device and capabilityes from linuxpy.

**Comment by tiagocoutinho** [comment]
Could you send a `ls -l /dev/video*` please?
Also the groups your user belongs to?
It might be a permissions issue
